# Generated by Django 3.0.1 on 2020-01-01 07:39

import app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='accounts.Profile')),
                ('credits', models.IntegerField(default=500)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('player_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=63)),
                ('image', models.ImageField(default='media/player_pics/dimaggio.jpg', upload_to='media/player_pics')),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('name', models.CharField(max_length=20)),
                ('abbrev', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('scoring_code', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('team_symbol', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=31)),
                ('city', models.CharField(max_length=31)),
                ('state', models.CharField(max_length=2)),
                ('stadium', models.CharField(max_length=31)),
                ('league', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='HitterStats',
            fields=[
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.Player')),
                ('avg', models.DecimalField(decimal_places=3, max_digits=5)),
                ('slg', models.DecimalField(decimal_places=3, max_digits=5)),
                ('ops', models.DecimalField(decimal_places=3, max_digits=5)),
                ('hits', models.IntegerField()),
                ('hr', models.IntegerField()),
                ('rbi', models.IntegerField()),
                ('so', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PitcherStats',
            fields=[
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.Player')),
                ('throws', models.CharField(max_length=1)),
                ('k_per_9', models.DecimalField(decimal_places=2, max_digits=5)),
                ('bb_per_9', models.DecimalField(decimal_places=2, max_digits=5)),
                ('k_bb', models.DecimalField(decimal_places=2, max_digits=5)),
                ('era', models.DecimalField(decimal_places=2, max_digits=5)),
                ('innings', models.DecimalField(decimal_places=1, max_digits=5)),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Position'),
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Team'),
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signed', models.BooleanField(default=app.models.is_signed)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Deck')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Player')),
            ],
        ),
    ]
