# Generated by Django 3.0.1 on 2019-12-29 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('scoring_code', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=15)),
                ('abbrev', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('team_symbol', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=31)),
                ('city', models.CharField(max_length=31)),
                ('state', models.CharField(max_length=2)),
                ('stadium', models.CharField(max_length=31)),
                ('league', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('player_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=63)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Position')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Team')),
            ],
        ),
    ]
