# Generated by Django 3.0.1 on 2020-01-02 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_comment_offer_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='offer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.Offer'),
        ),
    ]
